### ISSUE TITLE
So when is this going to get updated for 1.17?

### ISSUE THREAD

**Issue by 1schlick** [Lunaar-SMP/lunaar-carpet-addons#5]

**Comment by Copetan** [comment]
There's currently [a 1.17 branch](https://github.com/Lunaar-SMP/lunaar-carpet-addons/tree/1.17), but the latest commit doesn't compile, I'll fix that once I get to it and make a release.

There is no set release date.

**Comment by Copetan** [comment]
Check the [latest release](https://github.com/Lunaar-SMP/lunaar-carpet-addons/releases/tag/v0.5.0)
